#!name=Apple WLOC 定位修改
#!desc=修改 Apple 网络定位返回坐标 (Shadowrocket 小火箭) | 快捷指令(推荐): 设置地理位置 https://www.icloud.com/shortcuts/e50b5de193354a1bade3f116c16d9b42 清理恢复位置 https://www.icloud.com/shortcuts/35c2bab34b724046bdfb82bcf7b5172e | 选点页面: https://wloc-taqulalee.killer-100.workers.dev/
#!author=Yu9191 Rewrite
#!homepage=https://github.com/taqulalee/wloc
#!icon=https://raw.githubusercontent.com/taqulalee/wloc/refs/heads/codex/self-hosted-hardening/wloc.jpg
#!category=Tools

[Script]
Apple WLOC = type=http-response,pattern=^https?:\/\/(?:gs-loc(?:-cn)?\.apple\.com|gsp-ssl\.ls\.apple\.com)\/clls\/wloc,requires-body=1,binary-body-mode=1,max-size=0,timeout=30,script-path=https://raw.githubusercontent.com/taqulalee/wloc/refs/heads/codex/self-hosted-hardening/dist/wloc.js,argument=longitude=113.94114&latitude=22.544577&accuracy=25&logLevel=info
WLOC Settings = type=http-request,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/wloc-settings\/save,requires-body=0,max-size=0,timeout=10,script-path=https://raw.githubusercontent.com/taqulalee/wloc/refs/heads/codex/self-hosted-hardening/dist/wloc-settings.js

[MITM]
hostname = %APPEND% gs-loc.apple.com, gs-loc-cn.apple.com, gsp-ssl.ls.apple.com
